from solution_program import *
import pytest
import os
from solution_program import WordSearch

@pytest.fixture
def sample_grid():
    return WordSearch(['DOG', 'CAT', 'BIRD'])

@pytest.fixture(autouse=True)
def setup_and_teardown_files():
    """Setup and remove any files if needed for tests."""
    yield
    # Remove files if generated by tests

def test_grid_initialization(sample_grid):
    assert sample_grid.grid == [
        ['D', 'O', 'G', 'X'],
        ['C', 'A', 'T', 'X'],
        ['B', 'I', 'R', 'D'],
        ['X', 'X', 'X', 'X']
    ]

def test_word_exists_horizontally(sample_grid):
    assert sample_grid.exists('DOG') is True

def test_word_exists_vertically(sample_grid):
    assert sample_grid.exists('CAT') is True

def test_word_does_not_exist(sample_grid):
    assert sample_grid.exists('RAT') is False

def test_word_outside_grid(sample_grid):
    assert sample_grid.exists('FISH') is False

@pytest.mark.parametrize("words,expected_exception", [
    (['ELEPHANT'], ValueError),
])
def test_invalid_words_raise_exception(words, expected_exception):
    with pytest.raises(expected_exception):
        WordSearch(words)
