class WordSearch:
    def __init__(self, words: list):
        self.size = max(len(word) for word in words)
        for word in words:
            if len(word) > self.size:
                raise ValueError("Word length exceeds the grid size")
        self.grid = [['X'] * self.size for _ in range(self.size)]
        self._place_words(words)

    def _place_words(self, words: list):
        row, col = 0, 0
        for word in words:
            if col + len(word) <= self.size:
                for i, char in enumerate(word):
                    self.grid[row][col + i] = char
                row += 1
            elif row + len(word) <= self.size:
                for i, char in enumerate(word):
                    self.grid[row + i][col] = char
                col += 1
            else:
                break

    def exists(self, word: str) -> bool:
        # Check horizontal
        for row in self.grid:
            if ''.join(row).find(word) != -1:
                return True

        # Check vertical
        for col in range(self.size):
            column = ''.join(self.grid[row][col] for row in range(self.size))
            if column.find(word) != -1:
                return True

        return False

# Test suite
import pytest
import os
from solution import WordSearch

@pytest.fixture
def sample_grid():
    return WordSearch(['DOG', 'CAT', 'BIRD'])

@pytest.fixture(autouse=True)
def setup_and_teardown_files():
    """Setup and remove any files if needed for tests."""
    yield
    # Remove files if generated by tests

def test_grid_initialization(sample_grid):
    assert sample_grid.grid == [
        ['D', 'O', 'G', 'X'],
        ['C', 'A', 'T', 'X'],
        ['B', 'I', 'R', 'D'],
        ['X', 'X', 'X', 'X']
    ]

def test_word_exists_horizontally(sample_grid):
    assert sample_grid.exists('DOG') is True

def test_word_exists_vertically(sample_grid):
    assert sample_grid.exists('CAT') is True

def test_word_does_not_exist(sample_grid):
    assert sample_grid.exists('RAT') is False

def test_word_outside_grid(sample_grid):
    assert sample_grid.exists('FISH') is False

@pytest.mark.parametrize("words,expected_exception", [
    (['ELEPHANT'], ValueError),
])
def test_invalid_words_raise_exception(words, expected_exception):
    with pytest.raises(expected_exception):
        WordSearch(words)
